fieldLayouts:
  0ed317ef-116e-452b-aab3-3eab6ca75807:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b777f9bb-d87c-4a8d-b289-5ddd6ef46b83
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0f2c6c9a-3092-47f2-b0dc-46d8ce11c178 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d74ff3de-5344-4bec-aba8-4c78d3c75073
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8aa229ec-7643-48c3-947d-9d2c1882b8f2 # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b5acf38-7080-4134-8fbb-3a186379a87e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0dc6c354-b9bd-4fde-a895-7fa044b2d819
        userCondition: null
handle: fourOhFour
hasTitleField: false
name: '404'
section: f25c8355-39cc-443c-87cf-f23bf383449f # 404
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
